// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdH_ft2TPzY_OJVG228UBejKxntN6uSHM',
    appId: '1:472730669837:web:06dad38be751b038375644',
    messagingSenderId: '472730669837',
    projectId: 'esp-scale',
    authDomain: 'esp-scale.firebaseapp.com',
    databaseURL: 'https://esp-scale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-scale.appspot.com',
    measurementId: 'G-E28THFM70M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lJ_uKI-s_QASFbfv4j-SsPjGD4Vm6aM',
    appId: '1:472730669837:android:305bac593324339e375644',
    messagingSenderId: '472730669837',
    projectId: 'esp-scale',
    databaseURL: 'https://esp-scale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-scale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FDQxTs-6eT1KzGaxy0TyMTyGMsHWAIE',
    appId: '1:472730669837:ios:7c953af44830463d375644',
    messagingSenderId: '472730669837',
    projectId: 'esp-scale',
    databaseURL: 'https://esp-scale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-scale.appspot.com',
    iosClientId: '472730669837-asoo29hami6b6laidftigolrjnbnie9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.trngetiau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FDQxTs-6eT1KzGaxy0TyMTyGMsHWAIE',
    appId: '1:472730669837:ios:7c953af44830463d375644',
    messagingSenderId: '472730669837',
    projectId: 'esp-scale',
    databaseURL: 'https://esp-scale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-scale.appspot.com',
    iosClientId: '472730669837-asoo29hami6b6laidftigolrjnbnie9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.trngetiau',
  );
}
